apiVersion: v1
kind: Service
metadata:
  name: nginx-deployment-service
  namespace: dev
  labels: 
    app: nginx
spec:
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 80
  type: NodePort